/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MiBoton {
        "disabledButtonText": string;
        "texto": string;
    }
    interface MiCabecera {
    }
    interface MiTabla {
        "buttonText": string;
        "disabledButtonText": string;
        "dniTitle": string;
        "indiceTitle": string;
        "nombreTitle": string;
    }
}
export interface MiBotonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMiBotonElement;
}
declare global {
    interface HTMLMiBotonElement extends Components.MiBoton, HTMLStencilElement {
    }
    var HTMLMiBotonElement: {
        prototype: HTMLMiBotonElement;
        new (): HTMLMiBotonElement;
    };
    interface HTMLMiCabeceraElement extends Components.MiCabecera, HTMLStencilElement {
    }
    var HTMLMiCabeceraElement: {
        prototype: HTMLMiCabeceraElement;
        new (): HTMLMiCabeceraElement;
    };
    interface HTMLMiTablaElement extends Components.MiTabla, HTMLStencilElement {
    }
    var HTMLMiTablaElement: {
        prototype: HTMLMiTablaElement;
        new (): HTMLMiTablaElement;
    };
    interface HTMLElementTagNameMap {
        "mi-boton": HTMLMiBotonElement;
        "mi-cabecera": HTMLMiCabeceraElement;
        "mi-tabla": HTMLMiTablaElement;
    }
}
declare namespace LocalJSX {
    interface MiBoton {
        "disabledButtonText"?: string;
        "onButtonPressed"?: (event: MiBotonCustomEvent<any>) => void;
        "texto"?: string;
    }
    interface MiCabecera {
    }
    interface MiTabla {
        "buttonText"?: string;
        "disabledButtonText"?: string;
        "dniTitle"?: string;
        "indiceTitle"?: string;
        "nombreTitle"?: string;
    }
    interface IntrinsicElements {
        "mi-boton": MiBoton;
        "mi-cabecera": MiCabecera;
        "mi-tabla": MiTabla;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mi-boton": LocalJSX.MiBoton & JSXBase.HTMLAttributes<HTMLMiBotonElement>;
            "mi-cabecera": LocalJSX.MiCabecera & JSXBase.HTMLAttributes<HTMLMiCabeceraElement>;
            "mi-tabla": LocalJSX.MiTabla & JSXBase.HTMLAttributes<HTMLMiTablaElement>;
        }
    }
}
